In [1]:
from LabelEncoder import LabelEncoder
from sklearn.preprocessing import LabelEncoder as skLE
import numpy as np
import pandas as pd

In [2]:
y_train = ["paris", "paris", "tokyo", '-1', -1.0, -999, 'foo']
y_test1 = ["paris", "tokyo", "paris", -999, np.nan]
y_test2 = ["paris", "paris", "tokyo", "tel aviv", "amsterdam", -999, np.nan]

### Default fit transform is equivalent to sklearn label encoder. 

In [3]:
skle = skLE()

In [4]:
skle.fit_transform(y_train)

array([4, 4, 5, 0, 1, 2, 3])

In [5]:
skle.classes_

array(['-1', '-1.0', '-999', 'foo', 'paris', 'tokyo'],
      dtype='|S5')

In [6]:
le = LabelEncoder()

In [7]:
le.fit_transform(y_train)

array([0, 0, 1, 3, 2, 5, 4], dtype=object)

In [8]:
le.classes

0    paris
1    tokyo
2       -1
3       -1
4      foo
5     -999
dtype: object

In [9]:
le.most_common_class

'paris'

In [10]:
le.unknown_classes

[]

### Fit transform with nan classes defined and retained. 

In [11]:
le = LabelEncoder(retain_nan=True)

In [12]:
y_train.append(np.nan)

In [13]:
le.fit_transform(y_train)

array([0, 0, 1, 3, 2, 5, 4, nan], dtype=object)

### Fit and transform with different train and test data

In [14]:
le = LabelEncoder(retain_nan=True)

In [15]:
le.fit(y_train)

In [16]:
le.classes

0    paris
1    tokyo
2       -1
3       -1
4      foo
5     -999
dtype: object

In [17]:
le.transform(y_test1)

array([0, 1, 0, 5, nan], dtype=object)

In [18]:
le.transform(y_test2)

LabelEncoder.py:49: UserWarning: y contains new labels!
  warnings.warn("y contains new labels!")


array([0, 0, 1, 0, 0, 5, nan], dtype=object)

In [19]:
le.unknown_classes

{'amsterdam', 'tel aviv'}