In [1]:
from LabelEncoder import LabelEncoder
import numpy as np
import pandas as pd

In [2]:
y_train = ["paris", "paris", "tokyo", '-1',  np.nan, -1.0, -999, 'foo']
y_test1 = ["paris", "tokyo", "paris", -999]
y_test2 = ["paris", "paris", "tokyo", "tel aviv", "amsterdam", -999, np.nan]

### Default fit transform is equivalent to sklearn label encoder. 

In [3]:
le = LabelEncoder()

In [4]:
le.fit_transform(y_train)

array([5, 5, 6, 3, 0, 2, 1, 4])

### Fit transform with nan classes defined and retained. 

In [5]:
le = LabelEncoder(nan_classes=[np.nan, -1.0, '-1', -999, 'foo'], 
                  retain_nan=True)

In [6]:
le.fit_transform(y_train)

array([5, 5, 6, '-1', nan, -1.0, -999, 'foo'], dtype=object)

### Fit and transform with different train and test data

In [7]:
le = LabelEncoder()

In [8]:
le.fit(y_train)

In [9]:
le.classes

0    paris
1    tokyo
2       -1
3      NaN
4       -1
5     -999
6      foo
dtype: object

In [10]:
le.transform(y_test1)

array([0, 1, 0, 5], dtype=object)

In [11]:
le.transform(y_test2)

LabelEncoder.py:52: UserWarning: y contains new labels!
  warnings.warn("y contains new labels!")


array([0, 0, 1, 7, 7, 5, 3], dtype=object)

In [12]:
le = LabelEncoder(nan_classes=[np.nan, -1.0, '-1', -999, 'foo'], retain_nan=True)

In [13]:
le.fit(y_train)

In [14]:
le.classes

0    paris
1    tokyo
dtype: object

In [15]:
le.transform(y_test2)

array([0, 0, 1, 2, 2, -999, nan], dtype=object)

In [16]:
le.transform(y_test1)

array([0, 1, 0, -999], dtype=object)

In [17]:
le.inverse_transform(np.array([0, 1, 2]))

LabelEncoder.py:73: UserWarning: y contains unknown labels
  warnings.warn("y contains unknown labels")


array(['paris', 'tokyo', 'unknown'], dtype=object)